Add conda-forge to INSTALLATION.md.
Without conda-forge, some packages are missing.

```
PackagesNotFoundError: The following packages are not available from current channels:

  - pysmt=0.9*
  - ipykernel=6.29*
  - flask-cors=4.0*
  - bitarray=2.6*
```